{{/* ------------------------------------------------------------------------ */}}
{{- range $name, $raw := .Values.components }}
{{- $spec := mustMergeOverwrite (deepCopy $.Values.componentDefaults) (deepCopy $raw) }}
{{- if and $spec.enabled $spec.files }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-stack.componentName" (dict "root" $ "name" $name) }}
  labels:
    {{- include "generic-stack.labels" (dict "root" $ "name" $name "spec" $spec) | nindent 4 }}
data:
{{- range $fileName, $content := $spec.files }}
  {{ $fileName }}: |
{{ tpl $content $ | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
