{{/* ------------------------------------------------------------------------ */}}
{{- range $name, $raw := .Values.components }}
{{- $spec := mustMergeOverwrite (deepCopy $.Values.componentDefaults) (deepCopy $raw) }}
{{- if and $spec.enabled $spec.monitoring.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "generic-stack.componentName" (dict "root" $ "name" $name) }}
  labels:
    {{- include "generic-stack.labels" (dict "root" $ "name" $name "spec" $spec) | nindent 4 }}
    {{- with $spec.monitoring.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "generic-stack.selectorLabels" (dict "root" $ "name" $name) | nindent 6 }}
  podMetricsEndpoints:
    - port: {{ $spec.ports.admin.name }}
      path: /metrics
      interval: {{ $spec.monitoring.podMonitor.interval }}
{{- end }}
{{- end }}
