apiVersion: v2
name: generic-stack
description: Generic umbrella chart that deploys a values-defined set of container-build-standard components (default set - db, backend, frontend, proxy)
type: application
version: 0.0.1
appVersion: "0.0.1"
kubeVersion: ">=1.25.0-0"
